#!/usr/bin/bash

if [ $# = '0' ]; then
	list=./*/
else
	list=$@
fi

for dir in $list; do
	echo "$dir"
	read -p "Continue [y/n/s]? (y) " choice
	case "$choice" in
	  n|N ) exit;;
	  s|S ) continue;;
	esac
	if  grep -P '^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$' > /dev/null 2>&1 <<< $dir ; 
	then
		git clone  "$dir"
		d=$(sed 's/.*\/\(.*\)\.git/\1/g' <<< $dir)
	else
		d=$dir
	fi
	cd "$d" && git pull && makepkg -fi && cd ..
done
